
export default new Map([
["src/content/blog/akshardham-story.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fakshardham-story.mdx&astroContentModuleFlag=true")],
["src/content/blog/common-tourist-scams-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcommon-tourist-scams-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-in-the-monsoon.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-in-the-monsoon.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-metro-vs-cab-vs-auto.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-metro-vs-cab-vs-auto.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-night-safety-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-night-safety-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-rain-emergency-safety-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-rain-emergency-safety-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-situations-that-feel-unsafe.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-situations-that-feel-unsafe.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-street-food-safety-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-street-food-safety-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/delhi-traffic-survival-guide.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fdelhi-traffic-survival-guide.mdx&astroContentModuleFlag=true")],
["src/content/blog/first-24-hours-in-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffirst-24-hours-in-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/food-in-delhi-cultural-experience.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffood-in-delhi-cultural-experience.mdx&astroContentModuleFlag=true")],
["src/content/blog/guided-introducing-of-delhi-with-clarity.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fguided-introducing-of-delhi-with-clarity.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-a-concierge-thinks.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-a-concierge-thinks.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-avoid-getting-overcharged-in-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-avoid-getting-overcharged-in-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/personalizing-every-experience.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpersonalizing-every-experience.mdx&astroContentModuleFlag=true")],
["src/content/blog/police-uniformed-officers-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fpolice-uniformed-officers-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/situational-judgment-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsituational-judgment-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/talking-to-drivers-in-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftalking-to-drivers-in-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/why-delhi-feels-different.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhy-delhi-feels-different.mdx&astroContentModuleFlag=true")],
["src/content/blog/why-people-stare-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhy-people-stare-delhi.mdx&astroContentModuleFlag=true")],
["src/content/blog/yoga-in-delhi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fyoga-in-delhi.mdx&astroContentModuleFlag=true")]]);
		